name: Build App on Staging

on:
    push:
        branches:
            - "feat**"

jobs:
    Build-Budget-App-on-Staging:
        runs-on: ubuntu-latest
        timeout-minutes: 1

        env:
            # GASプロジェクトやclaspに関わる変数
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            ID_TOKEN: ${{ secrets.ID_TOKEN }}
            REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
            CLIENT_ID: ${{ secrets.CLIENTID }}
            CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
            SCRIPT_ID: ${{ secrets.SCRIPT_ID_STG }}
            # コード内で置換される変数
            TARGET_EMAIL_ADDRESS: ${{ secrets.TARGET_EMAIL_ADDRESS_STG }}
            TARGET_SHEET_NAME: "金銭メモstg"
            TEST_DATE: "20220207"

        steps:
            - name: リポジトリのチェックアウト
              uses: actions/checkout@v3

            - name: Node.jsのセットアップ
              uses: actions/setup-node@v3
              with:
                  node-version: "21"

            - name: 依存関係のキャッシュの復元
              uses: actions/cache@v3
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: 依存関係のインストール
              run: npm install

            - name: claspのインストール
              run: npm install -g @google/clasp

            - name: .clasprc.json の生成
              run: |
                  bash scripts/deployment/setup_clasprcjson.sh

            - name: .clasp.json の生成
              run: |
                  bash scripts/deployment/setup_claspjson.sh

            - name: メール送信先の変数置換
              run: |
                  sed -i 's/TARGET_EMAIL_ADDRESS/'"${TARGET_EMAIL_ADDRESS}"'/g' scripts/sendSummaryMail.js

            - name: TEST_DATE_PLACEHOLDER の置換(sendSummaryMail.js)
              run: |
                  sed -i 's/"TEST_DATE_PLACEHOLDER"/"${{ env.TEST_DATE }}"/g' scripts/sendSummaryMail.js

            - name: TEST_DATE_PLACEHOLDER の置換(addNewExpense.js)
              run: |
                  sed -i 's/"TEST_DATE_PLACEHOLDER"/"${{ env.TEST_DATE }}"/g' scripts/addNewExpense.js

            - name: メインスクリプトの変数置換
              run: |
                  sed -i 's/TARGET_SHEET_NAME/'"${TARGET_SHEET_NAME}"'/g' main.ts

            - name: スクリプト群のコピー
              run: make copy

            - name: カテゴリ一覧のコピー
              run: |
                  cp config/categories.js dist/categories.js

            - name: カテゴリ一覧スクリプトから不要文字列の削除
              run: |
                  sed -i '/^export default categories;/d' dist/categories.js

            - name: アプリのビルドとstg環境GASへのプッシュ
              run: make build-and-push
